# Generated by Django 5.0.6 on 2024-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
