# Generated by Django 4.2.9 on 2024-06-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cieliczko_pl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='fundacja_kochania_poznania',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='pomniki_poznania',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='poznanskie_legendy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='wspolna_sprawa',
            field=models.BooleanField(default=False),
        ),
    ]
