# Generated by Django 4.2.9 on 2024-06-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MonumentType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='monuments/')),
                ('description', models.TextField()),
                ('monument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonumentType.monumenttype')),
            ],
        ),
    ]
